Sarvesh/merkel patricia proof generator
OpenSTFoundation/openst-platform pull request #139
Opened 2018-06-27 12:18 UTC by sarvesh-ost

1. Exposed service to generate Account Proof
2. Exposed service to generate Storage Proof
3. Using singleton instance of leveldb
4. Using response helper and logger from openst-base
5. Unit test cases Proof generation, db factory, helper, library etc.

2018-07-04 14:49 UTC, abhayks1 requested changes

2018-07-04 14:49 UTC, abhayks1 commented on package.json
>      "node-cmd": "3.0.0",
Let's freeze these npm versions.

2018-07-04 14:49 UTC, abhayks1 commented on package.json
>    }
Let's also freeze these npm versions.

2018-07-05 17:09 UTC, kedarchandrayan approved these changes
All the changes which requested by me earlier have been incorporated. The PR looks good for merge.

2018-07-06 12:24 UTC, deepesh-kn reviewed
Added minor comments, other than variable name `StorageProof` and `storageProof` it looks good to me.

2018-07-06 12:24 UTC, deepesh-kn commented on test/unit/lib/proof/storage_proof_test.js
> +  let storageProofInstance, StorageProof, storageProof;
variable name `StorageProof` and `storageProof` is creating confusion. We should name it better.

2018-07-06 12:24 UTC, deepesh-kn commented on test/unit/lib/proof/account_proof_test.js
> +    AccountProof = require(rootPrefix + '/lib/proof/account_proof')
Any specific reason to have require here ? There are many such instances ex. line 48. (and also in other files.)

2018-07-06 12:24 UTC, deepesh-kn commented on lib/proof/proof.js
> +    internal_error_identifier: "l_p_accountProof_2",
Not so critical but like to mention here.

General observation:  we follow a pattern to create internal_error_identifier. 
Lets take this example, file path is `lib/proof/proof.js`, function name is `storageProof`
So the internal_error_identifier will be in this case: `l_p_p_storageProof_1`

If we are still following pattern then we need to update `internal_error_identifier` at multiple locations.

2018-07-09 10:13 UTC, sunilkhedar approved these changes
LGTM

2018-07-09 10:24 UTC, merged